keptn-contrib/artifacthub

artifacthub-repo.yml
prometheus/0.6.1/README.md
prometheus/0.6.1/artifacthub-pkg.yml

Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>

initial commit

---

generate_config.py

Automatically add keptn org to keywords

---

jenkins-library/5.0/README.md
jenkins-library/5.0/artifacthub-pkg.yml

- adds keptn-jenkins-library to our atrifacthub repo

Added keptn-jenkins-library

---

dynatrace/0.18.0/artifacthub-pkg.yml
dynatrace/0.18.1/artifacthub-pkg.yml

sets the Keptn version for dynatrace-service 0.18.0 and 0.18.1 to 0.10.0.

Set Keptn version on dynatrace-service to 0.10.0

---

jmeter/0.1.0/README.md

* upgraded to newest jmeter version - see https://jmeter.apache.org/changes.html
* fixes some things in the jmeter example:
* chmod +x entrypoint.sh is missing
* jmeter/basiccheck.jmx is not available in stage `staging` (but job-executor tries to fetch it and fails)
* although we are adding config.yaml in staging, we are executing jmeter test "basiccheck.jmx" - it should be "load.jmx"
* removes dynatrace extension (this example should really be a basic example)
* simplified wording a bit

chore: jmeter job-executor cleanup

---

CODEOWNERS

chore: Added codeowners file

---

prometheus/0.7.2/artifacthub-pkg.yml

- updates prometheus installation docs, which were outdated

fix: update prometheus installation docs

---

README.md

Added instructions on how to properly update an existing version of a service so that changes are reflected on Artifacthub. 
Related to #70

chore: Added updating instructions to README

---

CODEOWNERS

chore: Updated ownership of services

---

.github/workflows/ah_lint.yml

feat: Provide output of "ah lint" command as a pull request comment

---

.github/workflows/ah_lint_pr.yml

fix: Skipping lint action if no yml files changed. Fixes cp: missing destination error

---

powershell/1.0.0/README.md
powershell/1.0.0/artifacthub-pkg.yml

Signed-off-by: agardnerit <adam@agardner.net>

Add powershell integration

---

neoload/1.0.0/artifacthub-pkg.yml

Added digest and keptn/kind webhook to neoload integration

fix: add webhook and digest to neoload

---

locust/0.2/README.md
locust/0.2/artifacthub-pkg.yml

feat: Added Locust job executor integration

---

k6/1.0.0/README.md
k6/1.0.0/artifacthub-pkg.yml

Add k6 integration (thanks to @thschue for the inspiration and instructions :) )
Signed-off-by: adamgardnerit <adam@agardner.net>

Add k6 integration

---

datadog-service/0.15.0/README.md
datadog-service/0.15.0/artifacthub-pkg.yml

Signed-off-by: Suraj Banakar <surajrbanakar@gmail.com>

feat: add datadog SLI integration 0.15.0

---

powershell/1.0.0/README.md
powershell/1.0.0/artifacthub-pkg.yml

Instructions: powershell triggers keptn sequence + update compatible Keptn versions
Signed-off-by: agardnerit <adam@agardner.net>

Add: Powershell trigger sequence + Keptn versions

---

sumologic-service/0.15.0/README.md
sumologic-service/0.15.0/artifacthub-pkg.yml

Signed-off-by: Suraj Banakar <surajrbanakar@gmail.com>

feat: add SumoLogic SLI integration 0.15.0

---

infracost/1.0.0/artifacthub-pkg.yml

Fixes #153
Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com>

fix: Infracost logo url

---

CODEOWNERS
CONTRIBUTING.md
README.md

With this PR I would like to improve the REAMDE as well as the CODEOWNERS file.

Improve docs and codeowners file

---

jmeter/0.2.0/README.md
jmeter/0.2.0/artifacthub-pkg.yml

This PR improves jmeter job-executor installation instructions

docs: Improve jmeter installation instructions

---

helm/0.1.0/README.md
helm/0.1.0/artifacthub-pkg.yml

Applied similar wording (from PR https://github.com/keptn-contrib/artifacthub/pull/172 - thanks @StackScribe) changes to the Helm Job-Executor integration

feat: Improve wording for helm integration

---

datadog-service/0.15.0/artifacthub-pkg.yml
datadog-service/0.16.0/artifacthub-pkg.yml
datadog-service/0.17.0/artifacthub-pkg.yml
datadog-service/0.18.1/artifacthub-pkg.yml
datadog-service/0.19.0/artifacthub-pkg.yml

Fixes: https://github.com/keptn-sandbox/datadog-service/issues/76

feat: Add logo and fix the display name of the datadog-service integration in ArtifactHub

---

argo-jes/0.1.0/README.md
argo-jes/0.1.0/artifacthub-pkg.yml

- Adds Argo Job-Executor example

feat: Add Argo JES example

---

artillery/0.3.1/artifacthub-pkg.yml

close #194 
Signed-off-by: Tarang Verma <tarangverma004@gmail.com>

fix: changed logoURL from keptn-sandbox to keptn-contrib

---

tracetest/1.0.0/README.md
tracetest/1.0.0/artifacthub-pkg.yml

Hi folks!
This is the documentation presented on the Keptn community call this morning, with the details on how to integrate Tracetest with Keptn.

chore(docs): adding Tracetest integration on Keptn

---

CODEOWNERS
splunk-sli-provider/0.1.0/README.md
splunk-sli-provider/0.1.0/artifacthub-pkg.yml

Signed-off-by: kuro-jojo <kurojojo08@gmail.com>
- **Splunk logo** : we don't have a logo to use in the artifactory hub but we have contacted the splunk legal team to get the right to use their logo. Still in progress.

feat: add splunk sli provider 0.1.0

---

asana/1.0.0/README.md
asana/1.0.0/artifacthub-pkg.yml

This PR:
- Adds a notice deprecating the Keptn v1 Asana integration

Asana Service deprecation

---

.github/workflows/release_check.yml

Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>

limit new releases to 285 days
